theme: jekyll-theme-hacker
title: My learning path in cyber security
description: <div style="inline:block"> <script src="https://www.hackthebox.eu/badge/409359"></script> |  <script src="https://tryhackme.com/badge/62009"></script> </div>
