apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"webapp"},"name":"webapp-deployment","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"webapp"}},"template":{"metadata":{"labels":{"app":"webapp"}},"spec":{"containers":[{"image":"localhost:5000/node_server","imagePullPolicy":"Always","name":"webapp","ports":[{"containerPort":3000}],"volumeMounts":[{"mountPath":"/root/","name":"user-flag"}]}],"volumes":[{"hostPath":{"path":"/opt/user/"},"name":"user-flag"}]}}}}
  creationTimestamp: "2021-01-17T07:11:41Z"
  generation: 3
  labels:
    app: webapp
  name: webapp-deployment
  namespace: default
  resourceVersion: "19291"
  uid: bf4f491d-a226-4bd8-b497-297b425b5dfc
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: localhost:5000/node_server
        imagePullPolicy: Always
        name: webapp
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/
          name: user-flag
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/user/
          type: ""
        name: user-flag
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-01-17T07:11:41Z"
    lastUpdateTime: "2021-02-15T18:15:18Z"
    message: ReplicaSet "webapp-deployment-5d764566f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-05-11T04:19:17Z"
    lastUpdateTime: "2021-05-11T04:19:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
